apiVersion: v1
kind: Secret
metadata:
  name: {{ template "artifactory.fullname" . }}-snyk-config
  labels:
    app: {{ template "artifactory.name" . }}
    chart: {{ template "artifactory.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
stringData:
  snykSecurityPlugin.properties: |-
{{ tpl ( .Files.Get "files/snyk/snykSecurityPlugin.properties" ) . | indent 4 }}
